service: default
runtime: python37

basic_scaling:
    max_instances: 1
    idle_timeout: 5m

resources:
    cpu: 2
    memory_gb: 8
    disk_size_gb: 10

entrypoint: gunicorn -b :$PORT main2:app --timeout 120s